name: Continous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [23]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm ci, build, and test
        run: |
          npm ci
          npm test
